### ISSUE TITLE
Debug prints in production library

### ISSUE THREAD

**Issue by aledalgrande** [Woopra/Woopra-iOS#1]
[These lines](https://github.com/Woopra/Woopra-iOS/blob/master/WoopraSDK/WPinger.swift#L82) are printing logs in our app when we include the Woopra pod and activate pings. Is it possible to disable them?

**Comment by aledalgrande** [comment]
Also [this](https://github.com/Woopra/Woopra-iOS/blob/3f00c7cdb8522078ecad25cd626eebb85a36b8c1/WoopraSDK/WTracker.swift#L135)

**Comment by aledalgrande** [comment]
No help?

**Comment by philosoralphter** [comment]
hi @aledalgrande. 

Sorry I didn't see your message in December.  Let's see.  I'll have a chat over here about it, and see if we want to just comment those lines or what.  I'll get back to you asap.

--Ralph
